version: "3.9"

services:

  postgres-db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  client:
    build: client
    image: client
    volumes:
      - ./client:/source
    command: /bin/bash -c "cd /source/; npm i; npm run dev"
    ports:
      - 5173:5173

  web:
    build: .
    image: web_project
    links:
      - postgres-db:db
    volumes:
      - .:/source
      - static:/project/static 
      - media:/project/media
    depends_on:
      - postgres-db
    env_file:
      - .env
    command: "/bin/bash -c 'pip install -r requirements.txt; invoke run'"

  nginx:
    image: nginx
    links:
      - web:web
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/project/static:ro
      - media:/project/media:ro
    ports:
      - "8000:80"
      
volumes:
  pgdata: {}
  static: {}
  media: {}