version: "3.9"

services:

  postgres-db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis
  
  celery:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/source
      - static:/project/static 
      - media:/project/media
    command:
      /bin/bash -c "pip install -r requirements.txt; celery -A config.celery worker -l INFO"
    depends_on:
      - postgres-db
      - redis
      - web
    expose:
      - "80"

  web:
    build: .
    image: web_project
    restart: unless-stopped
    links:
      - postgres-db:db
    volumes:
      - .:/source
      - static:/project/static 
      - media:/project/media
    depends_on:
      - postgres-db
    env_file:
      - .env
    command: "/bin/bash -c 'pip install -r requirements.txt; invoke run'"

  nginx:
    image: nginx
    restart: unless-stopped
    links:
      - web:web
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/project/static:ro
      - media:/project/media:ro
      - ./client:/source:ro
    ports:
      - "80:80"
      
volumes:
  pgdata: {}
  static: {}
  media: {}