# Generated by Django 4.1.1 on 2022-09-17 08:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymus', max_length=50, null=True, verbose_name='name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='phone_number')),
                ('email', models.EmailField(blank=True, max_length=240, null=True, verbose_name='email')),
                ('message', models.TextField(max_length=500, null=True, verbose_name='message')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymus', max_length=50, null=True, verbose_name='name')),
                ('comment', models.TextField(max_length=500, null=True, verbose_name='comment')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date')),
                ('rate', models.CharField(choices=[('1', 'Very Dissatisfied'), ('2', 'Dissatisfied'), ('3', 'Good'), ('4', 'Satisfied'), ('5', 'Very Satisfied')], max_length=1, verbose_name='rate')),
            ],
        ),
    ]
